<h1>Tweet Searcher!</h1>
<?
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<?= $this->formRow($form->get('search')); ?>
<p>
    <input value="Search" type="submit" />
</p>
<?= $this->form()->closeTag() ?>

<? if ($this->tweets) : ?>
<table class="table">
    <thead>
        <tr>
            <th>User</th>
            <th>Tweet</th>
        </tr>
    </thead>
    <tbody>
        <? foreach ($this->tweets->toValue() as $group): ?>
            <? foreach ($group as $tweet):  ?>
                <? if ($tweet->user->name && $tweet->text) : ?>
                <tr>
                    <td><?= $tweet->user->name ?></td>
                    <td><?= $tweet->text ?></td>
                </tr>
                <? endif; ?>
            <? endforeach ?>
        <? endforeach; ?>
    </tbody>
</table>
<? endif; ?>